name: update

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "generate.sh"
      - ".github/workflows/update.yml"
jobs:
  update:
    if: github.repository == 'ecalose/caddys'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3 
          check-latest: true
      - name: update
        run: |
            bash generate.sh
            
      - 
        name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./caddy-*"
          tag: latest
          removeArtifacts: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
